#!/usr/bin/env python3
"""
End-to-end helper: download official maps, generate updated maps, package them.

Example:
    python build_map_package.py switzerland
    python build_map_package.py switzerland --label Switzerland
    python build_map_package.py switzerland --name IGPSport300-800-Switzerland.zip
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

from package_maps import COUNTRY_LABELS

DEFAULT_WORK_ROOT = "tmp"
DEFAULT_PACKAGE_DIR = "packages"


def safe_slug(parts):
    """Create a filesystem-safe slug from region terms."""
    text = "-".join(parts) if parts else "maps"
    text = re.sub(r"[^A-Za-z0-9._-]+", "-", text).strip("-")
    return text.lower() or "maps"


def display_label(parts):
    """Create a nice package label from region terms."""
    if len(parts) == 1:
        normalized = parts[0].strip().lower()
        for label in COUNTRY_LABELS.values():
            if label.lower() == normalized:
                return label

    return "-".join(part.strip().replace(" ", "-").title() for part in parts if part.strip())


def run_command(command, dry_run=False):
    """Run or print a subprocess command."""
    printable = " ".join(str(part) for part in command)
    print(f"> {printable}")
    if dry_run:
        return

    env = os.environ.copy()
    env["PYTHON"] = sys.executable
    subprocess.run(command, check=True, env=env)


def workflow_commands(args, input_dir):
    """Build the subprocess command list for the workflow."""
    commands = [
        [
            sys.executable,
            "download_igpsport_maps.py",
            *args.region,
            "--download",
            "--resume",
            "-o",
            str(input_dir),
        ],
    ]

    if args.keep_zip:
        commands[0].append("--keep-zip")

    if os.name == "nt":
        commands.append([
            "powershell",
            "-NoProfile",
            "-ExecutionPolicy",
            "Bypass",
            "-File",
            "run.ps1",
            str(input_dir),
            "-Resume",
        ])
    else:
        commands.append(["bash", "run.sh", str(input_dir), "--resume"])

    package_command = [
        sys.executable,
        "package_maps.py",
        str(input_dir),
        "--package-dir",
        args.package_dir,
    ]

    if args.output_dir != "output":
        package_command.extend(["--output-dir", args.output_dir])

    if args.name:
        package_command.extend(["--name", args.name])
    elif args.label:
        package_command.extend(["--label", args.label])
    else:
        package_command.extend(["--label", display_label(args.region)])

    commands.append(package_command)
    return commands


def main():
    parser = argparse.ArgumentParser(
        description="Download official iGPSPORT maps, generate updated maps, and package a ZIP."
    )
    parser.add_argument(
        "region",
        nargs="+",
        help="Region terms to download, e.g. switzerland or czech republic",
    )
    parser.add_argument(
        "--work-root",
        default=DEFAULT_WORK_ROOT,
        help=f"Working root for downloaded originals (default: {DEFAULT_WORK_ROOT})",
    )
    parser.add_argument(
        "--package-dir",
        default=DEFAULT_PACKAGE_DIR,
        help=f"Directory for the generated ZIP package (default: {DEFAULT_PACKAGE_DIR})",
    )
    parser.add_argument(
        "--output-dir",
        default="output",
        help="Directory containing/generated by the map build step (default: output)",
    )
    parser.add_argument(
        "--label",
        help="Override package label, e.g. Switzerland",
    )
    parser.add_argument(
        "--name",
        help="Override full ZIP filename",
    )
    parser.add_argument(
        "--keep-zip",
        action="store_true",
        help="Keep official downloaded ZIP files in the work input directory",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the commands without running them",
    )
    parser.add_argument(
        "--clean-work",
        action="store_true",
        help="Delete this workflow's downloaded input work folder after a successful package build",
    )
    args = parser.parse_args()

    slug = safe_slug(args.region)
    work_dir = Path(args.work_root) / f"igpsport-official-{slug}"
    input_dir = work_dir / "input"
    input_dir.mkdir(parents=True, exist_ok=True)

    print(f"Region: {' '.join(args.region)}")
    print(f"Input work dir: {input_dir}")
    print(f"Package dir: {args.package_dir}")
    print("")

    for command in workflow_commands(args, input_dir):
        run_command(command, dry_run=args.dry_run)

    if args.dry_run:
        print("\nDry run complete. No maps were downloaded or generated.")
    elif args.clean_work:
        shutil.rmtree(work_dir)
        print(f"\nRemoved work folder: {work_dir}")


if __name__ == "__main__":
    main()
