#!/usr/bin/env python3
"""
Experimental BiNavi workflow: generate the main map and package with official extras.

The official BiNavi package is used as a template. Router files and contour /
overview maps are copied unchanged; only the parseable main Maps/*.map file is
generated from OpenStreetMap.

Usage:
    uv run python build_binavi_package.py tmp/test-binavi/IT00
    uv run python build_binavi_package.py tmp/test-binavi/IT00 --dry-run
"""

import argparse
import os
import subprocess
import sys
from pathlib import Path

from .package_binavi import binavi_maps_dir, main_binavi_map, binavi_package_label

DEFAULT_PACKAGE_DIR = "packages"


def run_command(command, dry_run=False):
    printable = " ".join(str(part) for part in command)
    print(f"> {printable}")
    if dry_run:
        return

    env = os.environ.copy()
    env["PYTHON"] = sys.executable
    subprocess.run(command, check=True, env=env)


def workflow_commands(args):
    maps_dir = binavi_maps_dir(args.base_dir)

    if os.name == "nt":
        generate_command = [
            "powershell",
            "-NoProfile",
            "-ExecutionPolicy",
            "Bypass",
            "-File",
            "run.ps1",
            str(maps_dir),
            "-Resume",
        ]
    else:
        generate_command = ["bash", "run.sh", str(maps_dir), "--resume"]

    package_command = [
        sys.executable,
        "package_binavi.py",
        str(args.base_dir),
        "--package-dir",
        args.package_dir,
    ]

    if args.output_dir != "output":
        package_command.extend(["--output-dir", args.output_dir])

    if args.name:
        package_command.extend(["--name", args.name])
    elif args.label:
        package_command.extend(["--label", args.label])
    else:
        package_command.extend(["--label", binavi_package_label(main_binavi_map(args.base_dir))])

    return [generate_command, package_command]


def main():
    parser = argparse.ArgumentParser(
        description="Experimentally build a BiNavi package by replacing the main map only."
    )
    parser.add_argument(
        "base_dir",
        help="Official extracted BiNavi package folder containing Maps/ and Router/",
    )
    parser.add_argument(
        "--package-dir",
        default=DEFAULT_PACKAGE_DIR,
        help=f"Directory for the generated ZIP package (default: {DEFAULT_PACKAGE_DIR})",
    )
    parser.add_argument(
        "--output-dir",
        default="output",
        help="Directory containing/generated by the map build step (default: output)",
    )
    parser.add_argument(
        "--label",
        help="Override package label, e.g. Italy",
    )
    parser.add_argument(
        "--name",
        help="Override full ZIP filename",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print commands without generating or packaging",
    )
    args = parser.parse_args()
    args.base_dir = Path(args.base_dir)

    if not args.base_dir.is_dir():
        print(f"Error: base directory does not exist: {args.base_dir}", file=sys.stderr)
        sys.exit(1)

    try:
        main_map = main_binavi_map(args.base_dir)
    except ValueError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        sys.exit(1)

    print("Experimental BiNavi build")
    print(f"Base package: {args.base_dir}")
    print(f"Main map:     Maps/{main_map['filename']}")
    print("Preserved:    Router/ and non-standard Maps/*.map files")
    print("")

    for command in workflow_commands(args):
        run_command(command, args.dry_run)

    if args.dry_run:
        print("\nDry run complete. No maps were generated or packaged.")


if __name__ == "__main__":
    main()
